### ISSUE TITLE
clone problem: https://github.com/mkirsche/sv.git/ not found

### ISSUE THREAD

**Issue by fritzsedlazeck** [schatzlab/crossstitch#1]
git clone --recursive https://github.com/schatzlab/phase_sniffles.git
Cloning into 'phase_sniffles'...
remote: Counting objects: 391, done.
remote: Total 391 (delta 0), reused 0 (delta 0), pack-reused 391
Receiving objects: 100% (391/391), 2.35 MiB | 0 bytes/s, done.
Resolving deltas: 100% (177/177), done.
Submodule 'sv' (https://github.com/mkirsche/sv.git) registered for path 'sv'
Submodule 'vcf2diploid' (https://github.com/mschatz/vcf2diploid.git) registered for path 'vcf2diploid'
Cloning into '/Users/sedlazec/projects/github/phase_sniffles/sv'...
remote: Repository not found.
fatal: repository 'https://github.com/mkirsche/sv.git/' not found
fatal: clone of 'https://github.com/mkirsche/sv.git' into submodule path '/Users/sedlazec/projects/github/phase_sniffles/sv' failed
Failed to clone 'sv'. Retry scheduled
Cloning into '/Users/sedlazec/projects/github/phase_sniffles/vcf2diploid'...
remote: Counting objects: 25, done.
remote: Total 25 (delta 0), reused 0 (delta 0), pack-reused 25
Cloning into '/Users/sedlazec/projects/github/phase_sniffles/sv'...
remote: Repository not found.
fatal: repository 'https://github.com/mkirsche/sv.git/' not found
fatal: clone of 'https://github.com/mkirsche/sv.git' into submodule path '/Users/sedlazec/projects/github/phase_sniffles/sv' failed
Failed to clone 'sv' a second time, aborting

**Comment by fritzsedlazeck** [comment]
Actually its a permission thing.

**Comment by mschatz** [comment]
Correct, the refinement code is currently in a private repo

Mike

**Comment by mschatz** [comment]
This code is now fully integrated
