### ISSUE TITLE
Is it possible to integrate the phase information of SV calls?

### ISSUE THREAD

**Issue by JYLeeBioinfo** [schatzlab/crossstitch#11]
Hi

 I was wondering if phase information in SV VCF file itself can also be utilized by crossstitch to extend phase blocks.

 I use Sniffles with Nanopore long read data and since sniffles can give phase information for SVs that are linked in each of the spanning reads, I think it will lengthen the phase blocks to utilize phase information from sniffles.

**Comment by mschatz** [comment]
No, it is not used. You can use the long reads to phase any flanking SNPs,
though

Good luck

Mike

**Comment by JYLeeBioinfo** [comment]
Thank you for your reply!

With regards,
Jinyoung
