### ISSUE TITLE
phasing plant genome

### ISSUE THREAD

**Issue by yilunhuangyue** [schatzlab/crossstitch#3]
Hi,  Thank you for developing the tools. I am wondering if it can be used for phasing  plant genomes?By the way,  I have got pacbio reads and illumina reads, can I get phased_snps.vcf only by these  two kind of reads?
Thanks a lot for any suggestion.

**Comment by mschatz** [comment]
Most of it works independent of the genome, especially using the SNPs to phase SVs. However, the very last step that assembles the diploid genome only supports human right now, but only because there is some special logic in place to handle the sex chromosomes correctly. If this is a barrier to you, let me know any I can make some recommendations. And yes, you can use just Illumina and PacBio reads, although the phase blocks will be limited by the length of the PacBio reads. In human with a ~0.1% heterozygosity rate this averages to a phase block N50 length of around 250kb to 500kbp, although I would expect it to be more successful in a plant with higher rates of heterozygosity

Good luck!

Mike

**Comment by yilunhuangyue** [comment]
Hi Mike,
sorry for the late reply and thanks for your kind suggestion. I have tried a pipeline for haplotype assembly as follow steps.
 Firstly,I assembled a haplotype genome as reference(chromosome level). Then I sequenced the diploid genome in illumina and pacbio platform. The illumina read and pacbio reads were mapped to the reference and SNPs and SVs were called respectively. next, extractHAIRS were used to create fragment file for both pacbio and illumina reads, and I combined the two fragment file, the combined fragment was used by Hapcut2. Finally, I used crossstitch to assemble haplotypes, gender was set as "female" and refine was set as "0" and I did get the result. But there are some problems in the result. In theory, one haplotype sequence should be the same as reference, but I found SVs in both two haplotypes so they are both different from reference. I am not sure where is the problem. Is there any steps that could be corrected?
Thanks again.

Huang

**Comment by yilunhuangyue** [comment]
Hi Mike,
I have tried corssstitch for my genome and set refine to "1", but got an error message:
~/software/crossstitch/sv/process.sh: line 6: /crossstitch/testout2/inserts/*.txt.*: No such file or directory
I checked the source code and found that after running "java -cp "${BINDIR}" ReadFinder $WORKINGDIR/"${vcfFile}" $OUTDIR/inserts" in go.sh,  no files were created in "inserts" folders . But I did not find any error message, I don't known where is the problem. Could you give me any suggestions?

Best wishes,

Huang

**Comment by mschatz** [comment]
Hi Mike,

Is the crossstitch code up to date in the github repo? Otherwise, do you
have any suggestions as to why this might be failing?

Thanks!
Mike

**Comment by mschatz** [comment]
Hi Huang,

I think the first thing is to confirm that there are insertions in the VCF
file. Can you double check that is the case?

Thanks!

Mike

**Comment by yilunhuangyue** [comment]
Hi, I downloaded the latest version and tried again, but met the same error:
~/software/crossstitch-master/sv/process.sh: line 7: /corssstitch/testout3/inserts/*.txt.*: No such file or directory
By the way, my vcf file was created by sniffles  and there were "INS" .
And I noticed that the log file says"Number of insertions found: 5561
Number of insertions with supporting reads found: 0". Is there any error of my VCF file or mapping bam file?


Thanks

Huang

**Comment by yilunhuangyue** [comment]
Hi, I tried sniffles with parameter -n -1 and ran crossstitch again, and I got over this error now. Sorry for my mistake. But I met another error when running VCFEditor.java:
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at VCFEditor.main(VCFEditor.java:114)
Thanks for any suggestion.

**Comment by mschatz** [comment]
Would it be possible for you to share the data? That would really help us
to investigate the issues

Thanks!

Mike

**Comment by yilunhuangyue** [comment]
Hi Mike,

My data is unpublished now, so I did not leave the message on github. I am sorry if it troubles you.


You can download my data from http://211.69.140.136/download_tmp/. The original data is too big so I just put a part of my data on the web.  If you can't download the data or need more information, please let me known.


In addition, I comment out the code  for  handling the sex chromosomes when running corssstitch.


Thanks a lot for your kind help.

Huang


________________________________

**Comment by mschatz** [comment]
Thank you Huang. Im cc'ing my student Mike that worked on that part of the
pipeline. Mike, can you please take a look?

Mike

**Comment by fritzsedlazeck** [comment]
Dear Huang,

thanks for sharing. I just want to point out that this is visable on github.

Thanks
Fritz

**Comment by mschatz** [comment]
Hi Huang,


It appears that the alignment file (map.bam) has alignments to chromosomes other than chr1 (such as chr4), but these sequences are not present in the reference file you sent us (ref.fa).  Crossstitch requires that all the sequences which are aligned to be present in the reference file provided.  Could you please check whether or not this is the case for the version of the files you have?


Thanks,

Mike

________________________________

**Comment by yilunhuangyue** [comment]
Hi Mike,

The origin alignment file was too large so I just extracted the alignment file of chr1. Maybe I made some mistakes when extracting alignment file, so I upload the new alignment file(map.sort.bam) and SVs (map.sniffles-filt.vcf)today. In addition, I upload the log files for  running crossstitch.

And thanks Fritz for your kind reminding, I will delete the files aftering solving the problem.

Best wishes,

Huang

**Comment by mschatz** [comment]
Thanks! Mike, can you please try again

Mike

**Comment by mschatz** [comment]
Thanks for the updated files!  I was able to replicate the error (caused by an issue with the way I was handling relative vs absolute paths), and the most recent commit is a fix for it.  Please let me know if there continue to be issues.


Thanks,

Mike

________________________________

**Comment by yilunhuangyue** [comment]
Thanks Mike, this step is processed correctly but there are still two problems.

1. The last line in go.sh is "rm $WORKINGDIR/hs*.log", but I got the error message "rm: cannot remove `/test/hs*.log': No such file or directory", so I removed this line and ran program again and got final results.

2. I noticed the  most values of "REF" and "ALT" in refined VCF file  were  transferred to sequences  instead of "N" and `<INS>` or `<DEL>` in original vcf files. But when running "$BINDIR/scrubvcf.pl $OUTPREFIX.refined.vcf > $OUTPREFIX.scrubbed.vcf) >& $OUTPREFIX.scrubbed.log", only the lines which "ALT" is still `<INS>` or `<DEL>` were processed. In my case, the log file of  scrubvcf.pl show information like this:
`##` Reported 16 of 1447 variants:
`<DEL>` 0
`<INS>` 10
`<INV>` 6


And in *.spliced.vcf.svphase file, only these 16 SVs were phased. 

Could you please check this?

Thanks,

Huang

**Comment by mkirsche** [comment]
Hi,

I updated the scrubbing and splicing scripts to account for the format of
ref/alt alleles we are currently using, and it seems that all of the SVs
are making it into the spliced vcf file now.  Could you please let me know
it is working for you?

Thanks,
Mike

**Comment by yilunhuangyue** [comment]
Thanks Mike, it is working now.
By the way, how to cite corssstitch if I use it in my research.

Best Wishes,
Huang

**Comment by mschatz** [comment]
Great! Please cite the github repo for now -- we are working on a paper
this summer to describe it in more detail

Best

Mike
