### ISSUE TITLE
Issue with refineinsertions.sh 

### ISSUE THREAD

**Issue by CWYuan08** [schatzlab/crossstitch#7]
Hi there, I am now running crossstitch on my laptop and I tried refineinsertions.sh. However, I got this: 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path

The command I used: ./refineinsertions.sh raw.vcf Sorted.bam ref.fa outfile
How to use command this properly? 
Thank you very much

**Comment by mschatz** [comment]
Im guessing you are trying to run on mac, which uses different options for readlink than a linux machine. Unfortunately, only linux is supported at this time

Good luck
Mike
